routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('homepage');
Route::get('/contact_us','FrontendController@contact_us')->name('contact_us');
Route::get('/about_us','FrontendController@about_us')->name('about_us');
Route::get('/donor_register','FrontendController@register')->name('donor_register');
Route::get('/request','FrontendController@request')->name('request');
Route::get('/view_request','FrontendController@view_request')->name('view_request');
Route::get('/camps','FrontendController@camps')->name('camps');
Route::get('/signin','FrontendController@signin')->name('signin');
Route::get('/search','FrontendController@search')->name('search');
Route::get('/donorhelp','FrontendController@donorhelp')->name('donorhelp');
Route::get('/camp-images/{id}','FrontendController@allcampimages')->name('camp_galleries');


Route::resource('store_Donor','DonorRegistrationController');
Route::post('donor_login','DonorRegistrationController@donor_login')->name('donor_login');

Route::resource('store_request','RequestController');






Route::resource('contact','ContactController');

Route::resource('news','NewsController');
Route::resource('image','ImageController');



Route::get('/searchblood','DonorRegistrationController@searchblood')->name('searchblood');

Auth::routes();

Route::get('/register', function(){
    return redirect()->route('login');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin','middleware'=>['auth','admin']], function(){
    Route::get('/','HomeController@admin')->name('admin');
    Route::resource('camp','CampController');
    Route::resource('donor','DonorController');
    Route::resource('blood_request','AdminRequestController');
    Route::get('/profile','DonorController@adminProfile')->name('admin-profile');          
    Route::put('/profile/{id}','DonorController@UpdateAdmin')->name('admin-update');
    Route::resource('blood','BloodController');
    Route::resource('contact','ContactController');
});



Route::group(['prefix'=>'donor','middleware'=>['auth','donor']], function(){
    Route::get('/','HomeController@donor')->name('donor');
    Route::get('change_profile','DonorPanelController@change_profile')->name('change_profile');
    Route::put('update_profile/{id}','DonorPanelController@update_profile')->name('update_profile');
    Route::get('signout','DonorPanelController@signout')->name('signout');
    Route::resource('donorpanel','DonorPanelController');
    Route::get('donationhistory','DonorPanelController@donationhistory')->name('blood_history');
    Route::get('view_request','DonorPanelController@request_view')->name('request_view');
    Route::get('change_password','DonorPanelController@change_password')->name('change_password');
    Route::put('update_password/{id}','DonorPanelController@update_password')->name('update_password');

});

resources/views/admin/section/copy.blade.php
<footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>

resources/views/admin/section/footer.blade.php
</html>

resources/views/admin/section/header.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title') </title>

    <!-- Bootstrap -->
    <link href="{{asset('assets/admin/css/bootstrap.min.css')}}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{asset('assets/admin/css/all.min.css')}}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{{asset('assets/admin/css/nprogress.css') }}" rel="stylesheet">
    <!-- Animate.css -->
    <link href="{{ asset('assets/admin/css/animate.min.css')}}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{asset('assets/admin/css/custom.min.css')}}" rel="stylesheet">
    @yield('links');
  </head>

resources/views/admin/section/notification.blade.php
@if(session()->has('success'))
<p class="alert alert-success">
    {{ session('success') }}
    
   
</p>
@endif


@if(session()->has('error'))
<p class="alert alert-danger">
    {{ session('error') }}
</p>
@endif

<script>
setTimeout(function(){
$('.alert').slideUp();
}, 3000);
</script>

resources/views/admin/section/scripts.blade.php
 <!-- jQuery -->
 <script src="{{asset('assets/admin/js/jquery.min.js')}}"></script>
    <!-- Bootstrap -->
    <script src="{{asset('assets/admin/js/bootstrap.min.js')}}"></script>
    <!-- FastClick -->
    <script src="{{asset('assets/admin/js/fastclick.js')}}"></script>
    <!-- NProgress -->
    <script src="{{asset('assets/admin/js/nprogress.js')}}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{{asset('assets/admin/js/custom.js')}}"></script>

    @yield('scripts');

resources/views/admin/section/sidebar.blade.php
<div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="{{route('homepage')}}" class="site_title"><i class="fa fa-dove"></i> <span>Admin CMS!</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="{{ asset('images/users/'.request()->user()->image)}}" alt="No image found" class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ Auth::user()->name }}</h2>
              </div>
              <div class="clearfix"></div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
               
                <ul class="nav side-menu">
               
                  <li><a href="{{ route('donor.index')}}">Donor</a></li>
                  <li><a href="{{route('blood_request.index')}}"> Request </a></li>
                  <li><a href="{{route('image.index')}}"> Image  </a></li>
                  
                  <li><a href="{{route('camp.index')}}"> Camps </a></li>
                  <li><a href="{{route('news.index')}}">News </a></li>
                  <li><a href="{{route('blood.index')}}"> Blood  </a></li>
                  <li><a href="{{ route('contact.index')}}"> Contact </a></li>
                   
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

resources/views/admin/section/topnav.blade.php
<div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="images/img.jpg" alt="">{{ request()->user()->name}}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="{{ route('admin-profile')}}"> Profile</a></li>
                    <li>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <i class="fa fa-sign-out pull-right">
                                
                                </i> Log Out
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                        


                       
                        </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>