routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('homepage');
Route::get('/contact_us','FrontendController@contact_us')->name('contact_us');
Route::get('/about_us','FrontendController@about_us')->name('about_us');
Route::get('/donor_register','FrontendController@register')->name('donor_register');
Route::get('/request','FrontendController@request')->name('request');
Route::get('/view_request','FrontendController@view_request')->name('view_request');
Route::get('/camps','FrontendController@camps')->name('camps');
Route::get('/signin','FrontendController@signin')->name('signin');
Route::get('/search','FrontendController@search')->name('search');
Route::get('/donorhelp','FrontendController@donorhelp')->name('donorhelp');
Route::get('/camp-images/{id}','FrontendController@allcampimages')->name('camp_galleries');


Route::resource('store_Donor','DonorRegistrationController');
Route::post('donor_login','DonorRegistrationController@donor_login')->name('donor_login');

Route::resource('store_request','RequestController');






Route::resource('contact','ContactController');

Route::resource('news','NewsController');
Route::resource('image','ImageController');



Route::get('/searchblood','DonorRegistrationController@searchblood')->name('searchblood');

Auth::routes();

Route::get('/register', function(){
    return redirect()->route('login');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin','middleware'=>['auth','admin']], function(){
    Route::get('/','HomeController@admin')->name('admin');
    Route::resource('camp','CampController');
    Route::resource('donor','DonorController');
    Route::resource('blood_request','AdminRequestController');
    Route::get('/profile','DonorController@adminProfile')->name('admin-profile');          
    Route::put('/profile/{id}','DonorController@UpdateAdmin')->name('admin-update');
    Route::resource('blood','BloodController');
    Route::resource('contact','ContactController');
});



Route::group(['prefix'=>'donor','middleware'=>['auth','donor']], function(){
    Route::get('/','HomeController@donor')->name('donor');
    Route::get('change_profile','DonorPanelController@change_profile')->name('change_profile');
    Route::put('update_profile/{id}','DonorPanelController@update_profile')->name('update_profile');
    Route::get('signout','DonorPanelController@signout')->name('signout');
    Route::resource('donorpanel','DonorPanelController');
    Route::get('donationhistory','DonorPanelController@donationhistory')->name('blood_history');
    Route::get('view_request','DonorPanelController@request_view')->name('request_view');
    Route::get('change_password','DonorPanelController@change_password')->name('change_password');
    Route::put('update_password/{id}','DonorPanelController@update_password')->name('update_password');

});

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    protected $fillable =['title','status','image'];
    protected $table="images";


    public function getRules($options='add'){
        return [
            'title'=>'nullable|string',
           'image'=>(($options == 'add') ? 'required' : 'required').'|image|max:5000',
            'status'=>'required|in:active,inactive',
           
        ];
    }
}

app/Http/Controllers/ImageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Image;

class ImageController extends Controller
{
    protected $images = null;
    public function __construct(Image $images)
    {
        $this->images = $images;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->images = $this->images->orderBy('id','DESC')->get();

        return view('admin.images.index')->with('image_data', $this->images);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.images.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = $this->images->getRules();
        $request->validate($rules);

        $data = $request->all();

        if ($request->image) {
            $file_name = uploadImage($request->image, 'image');
            if ($file_name) {
                $data['image'] = $file_name;
            } else {
                $data['image'] = null;
            }
        }

        $this->images->fill($data);
        $success = $this->images->save();

        if ($success) {
            $request->session()->flash('success', 'Image added Successfully.');
        } else {
            $request->session()->flash('error', 'problem adding image');
        }
        return redirect()->route('image.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->images = $this->images->find($id);

        if (!$this->images) {
            request()->session()->flash('error', 'image does not found');
            return redirect()->route('image.index');
        }
        return view('admin.images.form')->with('image_data', $this->images);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = $this->images->getRules('update');
        $request->validate($rules);

        $data = $request->all();
        $this->images = $this->images->find($id);
        
        
        if($request->image){
            $file_name = uploadImage($request->image,'image');
        if($file_name){
            $data['image'] =$file_name;
            if(file_exists(public_path().'/images/image/'.$this->images->image))
                unlink(public_path().'/images/image/'.$this->images->image);
        }
    }
        
        
        $this->images->fill($data);
        $success = $this->images->save();

        if ($success) {
            $request->session()->flash('success', 'Image updated Successfully.');
        } else {
            $request->session()->flash('error', 'problem updating images');
        }
        return redirect()->route('image.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->images = $this->images->find($id);

        if (!$this->images) {
            request()->session()->flash('error', 'image not found');
            return redirect()->route('image.index');
        }
        $image = $this->images->image;
        $del = $this->images->delete();
        if ($del) {
            if (!empty($image) && file_exists(public_path() . '/images/image/' . $image)) {
                unlink(public_path() . '/images/image/' . $image);
            }
            request()->session()->flash('success', 'Image deleted successfully');
        } else {
            request()->session()->flash('error', ' problem deleting Image ');
        }

        return redirect()->route('image.index');
    }
}

resources/views/admin/images/form.blade.php
@extends('layouts.admin-dashboard')

@section('content')
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Image {{ isset($image_data) ? 'update' : 'add'}} </h3>

            </div>

            <div class="title_right">

            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>{{ isset($image_data) ? 'update' : 'add'}} Image</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        @if(isset($image_data))
                       {{Form::open(['url'=>route('image.update',$image_data->id),'class'=>'form', 'enctype'=>'multipart/form-data'])  }}
                            @method('PUT')

                        @else
                        {{Form::open(['url'=>route('image.store'),'class'=>'form', 'enctype'=>'multipart/form-data'])  }}

                        @endif
                        <div class="form-group row">
                            {{ Form::label('title', 'Title: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::text('title', @$image_data->title ,['class'=>'form-control','id'=>'title']) }}
                                @if($errors->has('title'))
                                <span class="alert-danger">{{ $errors->first('title') }}</span>
                                @endif
                            </div>
                        </div>
                      

                        <div class="form-group row">
                            {{ Form::label('status', 'Status: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::select('status',['active'=>"Active",'inactive'=>'Inactive'],@$image_data->status ,['class'=>'form-control','id'=>'status']) }}
                                @if($errors->has('status'))
                                <span class="alert-danger">{{ $errors->first('status') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('image', 'Image: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-4">
                                {{Form::file('image',['class'=>'form-control','id'=>'image','required'=> isset($image_data) ? false : true , 'accept'=>'image/*']) }}
                                @if($errors->has('image'))
                                <span class="alert-danger">{{ $errors->first('image') }}</span>
                                @endif
                            </div>
                            @if(isset($image_data) && file_exists(public_path().'/images/image/'.$image_data->image))
                            <div class="col-sm-4">
                                <img src="{{ asset('images/image/'.$image_data->image )}} " class="img img-responsive img-thumbnail">
                            </div>
                            @endif
                        </div>

                        <div class="form-group row">
                            {{ Form::label('', '',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::button('<i class ="fas fa-plane"></i> Submit',['class'=>'btn btn-success','id'=>'submit','type'=>'submit']) }}
                                {{Form::button('<i class ="fas fa-trash"></i> Cancel',['class'=>'btn btn-danger','id'=>'cancel','type'=>'reset']) }}

                            </div>
                        </div>


                        {{Form::close()}}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->

@endsection

resources/views/admin/images/index.blade.php
@extends('layouts.admin-dashboard')

@section('content')
               <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Image list</h3>

              </div>

              <div class="title_right">
              <a href="{{ route('image.create')}}" class="btn btn-success pull-right"><i class="fas fa-plus"></i> Add Image</a>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>All image</h2>

                    <div class="clearfix"></div>
                    @include('admin.section.notification')
                  </div>
                  <div class="x_content">
                     <table class="table jambo_table">
                        <thead>
                            <th>Title</th>
                            <th>Image</th>
                            
                            <th>Status</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            @if($image_data)
                                @foreach($image_data as $key=>$value)
                                    <tr>
                                        <td>{{ $value->title }}</td>
                                        <td>
                                            @if($value->image != null && file_exists(public_path().'/images/image/'.$value->image) )
                                        <img style="max-width:150px" src="{{ asset('images/image/'.$value->image)}}" alt="" class="img img-responsive img-thumbnail">
                                            @endif
                                        </td>
                                       
                                        <td>{{ ucfirst($value->status)}}</td>
                                        <td>
                                            <a href="{{ route('image.edit',$value->id)}}" style="border-radius: 50%" class="btn btn-success">
                                        <i class="fas fa-pencil-alt"></i></a>


                                        <form action="{{ route('image.destroy',$value->id)}}" onsubmit="return confirm('Are you sure to delete the image')" method="post">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-danger" style="border-radius: 50%">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>




                                        </td>
                                    </tr>
                                @endforeach
                            @endif

                        </tbody>
                     </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->

@endsection