routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('homepage');
Route::get('/contact_us','FrontendController@contact_us')->name('contact_us');
Route::get('/about_us','FrontendController@about_us')->name('about_us');
Route::get('/donor_register','FrontendController@register')->name('donor_register');
Route::get('/request','FrontendController@request')->name('request');
Route::get('/view_request','FrontendController@view_request')->name('view_request');
Route::get('/camps','FrontendController@camps')->name('camps');
Route::get('/signin','FrontendController@signin')->name('signin');
Route::get('/search','FrontendController@search')->name('search');
Route::get('/donorhelp','FrontendController@donorhelp')->name('donorhelp');
Route::get('/camp-images/{id}','FrontendController@allcampimages')->name('camp_galleries');


Route::resource('store_Donor','DonorRegistrationController');
Route::post('donor_login','DonorRegistrationController@donor_login')->name('donor_login');

Route::resource('store_request','RequestController');






Route::resource('contact','ContactController');

Route::resource('news','NewsController');
Route::resource('image','ImageController');



Route::get('/searchblood','DonorRegistrationController@searchblood')->name('searchblood');

Auth::routes();

Route::get('/register', function(){
    return redirect()->route('login');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin','middleware'=>['auth','admin']], function(){
    Route::get('/','HomeController@admin')->name('admin');
    Route::resource('camp','CampController');
    Route::resource('donor','DonorController');
    Route::resource('blood_request','AdminRequestController');
    Route::get('/profile','DonorController@adminProfile')->name('admin-profile');          
    Route::put('/profile/{id}','DonorController@UpdateAdmin')->name('admin-update');
    Route::resource('blood','BloodController');
    Route::resource('contact','ContactController');
});



Route::group(['prefix'=>'donor','middleware'=>['auth','donor']], function(){
    Route::get('/','HomeController@donor')->name('donor');
    Route::get('change_profile','DonorPanelController@change_profile')->name('change_profile');
    Route::put('update_profile/{id}','DonorPanelController@update_profile')->name('update_profile');
    Route::get('signout','DonorPanelController@signout')->name('signout');
    Route::resource('donorpanel','DonorPanelController');
    Route::get('donationhistory','DonorPanelController@donationhistory')->name('blood_history');
    Route::get('view_request','DonorPanelController@request_view')->name('request_view');
    Route::get('change_password','DonorPanelController@change_password')->name('change_password');
    Route::put('update_password/{id}','DonorPanelController@update_password')->name('update_password');

});

app/Models/Camp.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Camp extends Model
{
    protected $fillable=['title','details','date','status','organized_by','address','image','on','added_by'];

    public function getRules($options='add'){
        return [
            'title'=>'required|string',
             'organized_by'=>'required|string',
            'details'=>'nullable|string',
            'address'=>'required|string',
            'image'=>(($options == 'add') ? 'required' : 'sometimes').'|image|max:5000',
            'other_images.*'=>'sometimes|image|max:5000',
            'on'=>'required|date',
            'status'=>'required|in:active,inactive'
        ];
    }

    public function camp_images(){
        return $this->hasMany('App\Models\CampImages','camp_id','id');
    }

    public function getById($id){
        return $this->with('camp_images')->find($id);
    }
}

app/Http/Controllers/CampController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Camp;
use App\Models\CampImages;
use DB;

class CampController extends Controller
{
    protected $camp = null;
    protected $camp_images = null;
    public function __construct(Camp $camp)
    {
         $this->camp = $camp;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->camp = $this->camp->orderBy('id', 'DESC')->get();
        return view('admin.camps.index')->with('camp_data', $this->camp);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.camps.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = $this->camp->getRules();
        $request->validate($rules);

        $data = $request->all();
        $data['added_by'] = $request->user()->id;

        if ($request->image) {
            $file_name = uploadImage($request->image, 'camps');
            if ($file_name) {
                $data['image'] = $file_name;
            } else {
                $data['image'] = null;
            }
        }


        $this->camp->fill($data);
        $success = $this->camp->save();

        if ($success) {
            if ($request->other_images) {
                foreach ($request->other_images as $other_images) {
                    $file = uploadImage($other_images, 'camps');
                    if ($file) {
                        $temp = array(
                            'camp_id' => $this->camp->id,
                            'other_images' => $file
                        );
                        CampImages::insert($temp);
                    }
                }
            }
            $request->session()->flash('success', 'Camp added successfully');
        } else {
            $request->session()->flash('error', 'sorry please try again');
        }
        return redirect()->route('camp.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->camp = $this->camp->getById($id);
        if (!$this->camp) {
            request()->session()->flash('error', 'Camp not found.');
            return redirect()->route('camp.index');
        }
        return view('admin.camps.form')->with('edit_data', $this->camp);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = $this->camp->getRules('update');
        $request->validate($rules);

        $data = $request->all();

        $this->camp = $this->camp->find($id);

        if ($request->image) {
            $file_name = uploadImage($request->image, 'camps');
            if ($file_name) {
                $data['image'] = $file_name;

                if (file_exists(public_path() . '/images/camps/' . $this->camp->image)) {
                    unlink(public_path() . '/images/camps/' . $this->camp->image);
                }
            }
        }


        $this->camp = $this->camp->fill($data);
        $success = $this->camp->save();
        if ($success) {
            if ($request->other_images) {
                foreach ($request->other_images as $other_images) {
                    $file = uploadImage($other_images, 'camps');
                    if ($file) {
                        $temp = array(
                            'camp_id' => $this->camp->id,
                            'other_images' => $file,
                        );
                        CampImages::insert($temp);
                    }
                }
            }
            if (isset($request->del_image)) {
                foreach ($request->del_image as $del_image) {

                    $del = DB::table('camp_images')->where('other_images', '=', $del_image)->delete();
                    if ($del) {
                        if (file_exists(public_path() . '/images/camps/' . $del_image)) {
                            unlink(public_path() . '/images/camps/' . $del_image);
                        }
                    }
                }
            }
            $request->session()->flash('success', 'Camp updated successfully');
        } else {
            $request->session()->flash('error', 'Sorry, not updated at this time. Please try again');
        }
        return redirect()->route('camp.index');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->camp = $this->camp->find($id);
        if (!$this->camp) {
            request()->session()->flash('error', 'Camp not found');
            return redirect()->route('camp.index');
        }
        $image = $this->camp->image;
        $success = $this->camp->delete();
        if ($success) {
            if (!empty($image) && file_exists(public_path() . '/images/camps/' . $image)) {
                unlink(public_path() . '/images/camps/' . $image);
            }
            request()->session()->flash('success', 'Camp deleted successfully');
        } else {
            request()->session()->flash('error', 'Camp not deleted');
        }
        return redirect()->route('camp.index');
    }
}

resources/views/admin/camps/form.blade.php
@extends('layouts.admin-dashboard')

@section('title')
Admin !! {{ (isset($edit_data) && $edit_data->count() > 0) ? 'Edit' : 'Insert' }} camp
@endsection

@section('content')
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>{{ (isset($edit_data) && $edit_data->count() > 0) ? 'Edit' : 'Insert' }} camp details</h3>

      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">



          </div>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">

            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            @if( isset($edit_data) && $edit_data->count() > 0)
            <form action="{{ route('camp.update',$edit_data->id)}}" class="form" method="post" enctype="multipart/form-data">
              @method('PUT')
              @else
              <form action="{{ route('camp.store')}}" class="form" method="post" enctype="multipart/form-data">
                @endif
                @csrf
                <div class="form-group row">

                  <div class="col-sm-1">
                    <td> Title:</td>
                  </div>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="title" value='{{ @$edit_data->title }}'>
                    @if($errors->has('title'))
                    <span class="alert-danger">
                      {{$errors->first('title')}}
                    </span>
                    @endif
                  </div>
                </div>


                <div class="form-group row">
                  <div class="col-sm-1">
                    <td> Organizer:</td>
                  </div>
                  <div class="col-sm-9">
                    <input type="text" value='{{ @$edit_data->organized_by }}' class="form-control" name="organized_by">
                    @if($errors->has('organized_by'))
                    <span class="alert-danger">
                      {{$errors->first('organized_by')}}
                    </span>
                    @endif
                  </div>
                </div>


                <div class="form-group row">
                  <div class="col-sm-1">
                    <td> Details:</td>
                  </div>
                  <div class="col-sm-9">
                    <textarea class="form-control" rows="10" style="resize:none" name="details"> {{ @$edit_data->details  }} </textarea>
                    @if($errors->has('details'))
                    <span class="alert-danger">
                      {{$errors->first('details')}}
                    </span>
                    @endif
                  </div>
                </div>


                <div class="form-group row">
                  <div class="col-sm-1">
                    <td> Address:</td>
                  </div>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" name="address" value='{{ @$edit_data->address }}'>
                    @if($errors->has('address'))
                    <span class="alert-danger">
                      {{$errors->first('address')}}
                    </span>
                    @endif
                  </div>
                </div>


                <div class="form-group row">
                  <div class="col-sm-1">
                    <td> Date(on):</td>
                  </div>
                  <div class="col-sm-9">
                    <input type="date" class="form-control" name="on" value=<?php echo @$edit_data->on; ?>>
                    @if($errors->has('date'))
                    <span class="alert-danger">
                      {{$errors->first('date')}}
                    </span>
                    @endif
                  </div>
                </div>


                <div class="form-group row">
                  <div class="col-sm-1">
                    <td> Status:</td>
                  </div>
                  <div class="col-sm-9">
                    <select name="status" id="" class="form-control">
                      <option value="active" <?php echo (isset($edit_data) && @$edit_data->status == 'active') ? 'selected' : ''; ?>>Active</option>
                      <option value="inactive" <?php echo (isset($edit_data) && @$edit_data->status == 'inactive') ? 'selected' : ''; ?>>Inactive</option>
                    </select>
                    @if($errors->has('status'))
                    <span class="alert-danger">
                      {{$errors->first('status')}}
                    </span>
                    @endif
                  </div>
                </div>


                <div class="form-group row">
                  <div class="col-sm-1">
                    <td> image:</td>
                  </div>
                  <div class="col-sm-4">
                    <input type="file" class="form-control" accept="image/*" name="image" {{ (isset($edit_data) ? '' : 'required' ) }}>
                    @if($errors->has('image'))
                    <span class="alert-danger">
                      {{$errors->first('image')}}
                    </span>
                    @endif
                  </div>
                  @if(isset($edit_data) && file_exists(public_path().'/images/camps/'.$edit_data->image))
                  <div class="col-sm-4">
                    <img src="{{ asset('images/camps/'.$edit_data->image)}}" alt="sorry" class="img img-responsive img-thumbnail" width="150">
                  </div>
                  @endif
                </div>


                <div class="form-group row">
                  {{ Form::label('other_images','Other Image: ',['class'=>'col-sm-1']) }}
                  <div class="col-sm-4">
                    {{Form::file('other_images[]',['class'=>'form-control','id'=>'other_images','accept'=>'other_images/*','multiple'=>true]) }}
                    @if($errors->has('other_images'))
                    <span class="alert-danger">
                      {{ $errors->first('other_images') }}
                    </span>
                    @endif
                  </div>
                </div>
                @if(isset($edit_data, $edit_data->camp_images))

                @foreach($edit_data->camp_images as $images)

                <div class="col-sm-3">
                  <img src="{{ asset('images/camps/'.$images->other_images) }}" alt="" class="img img-responsive img-thumbnail" width="200px" height="auto">
                  {{ Form::checkbox('del_image[]',$images->other_images) }} Delete
                </div>
                @endforeach

                @endif






                <div class="form-group row">
                  <div class="col-sm-1">
                    <td></td>
                  </div>
                  <div class="col-sm-4">
                    <button name="submit" type="submit">Submit</button>
                    <input type="reset" name="reset" value="reset" type="reset">
                  </div>
                </div>



              </form>


          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /page content -->


@endsection

resources/views/admin/camps/index.blade.php
@extends('layouts.admin-dashboard')

@section('title')
      Admin !! Camp
@endsection

@section('links')
    <link rel="stylesheet" href="{{ asset('assets/admin/css/jquery.dataTables.min.css')}}">
@endsection

@section('scripts')
        <script src= "{{ asset('assets/admin/js/jquery.dataTables.min.js')}}" ></script>
        <script>
            $('.table').dataTable();

        </script>
@endsection

@section('content')
 <!-- page content -->
 <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Camp list</h3>
              
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
              

                    
                  </div>
                </div>
              </div>
              <a href="{{route('camp.create')}}" class="btn btn-success pull-right"><i class="fas fa-plus"></i>Add Camp</a>
            </div>

            <div class="clearfix"></div>
            @include('admin.section.notification')

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>All camp list</h2>
                   
                    
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                      <table class="table jambo_table">
                         <thead>

                          <th>S.n</th>
                          <th>Name</th>
                          
                          <th>Organized by</th>
                          <th>Details</th>
                          <th>Address</th>
                          <th>Status</th>
                          <th>On</th>
                          <th>Action</th>
                         </thead>
                         <tbody>
                             @if($camp_data)
                              @foreach($camp_data as $key=>$value)
                              <tr>
                                <th>{{$key+1}}</th>
                                 <td>{{$value->title}}</td>
                                
                                 <td>{{$value->organized_by}}</td>
                                 <td>{{$value->details}}</td>
                                 <td>{{$value->address}}</td>
                                 <td>{{ucfirst($value->status)}}</td>
                                 <td>{{$value->on}}</td>
                                <td><a href="{{route('camp.edit',$value->id)}}" style="border-radius:50%" class="btn btn-success"> <i class="fas fa-pencil-alt"></i></a>
                                  
                                <form action="{{ route('camp.destroy',$value->id)}}" method="post" onsubmit="return confirm('Are you sure to delete the camp data:')">
                                  @csrf
                                  @method('delete')
                                  <button class="btn btn-danger" style="border-radius:50%"> <i class="fas fa-trash"></i></button>

                                </form>
                                </td>
                              </tr>
                              @endforeach
                             @endif

                         </tbody>
                      </table>
                      
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->


@endsection