routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('homepage');
Route::get('/contact_us','FrontendController@contact_us')->name('contact_us');
Route::get('/about_us','FrontendController@about_us')->name('about_us');
Route::get('/donor_register','FrontendController@register')->name('donor_register');
Route::get('/request','FrontendController@request')->name('request');
Route::get('/view_request','FrontendController@view_request')->name('view_request');
Route::get('/camps','FrontendController@camps')->name('camps');
Route::get('/signin','FrontendController@signin')->name('signin');
Route::get('/search','FrontendController@search')->name('search');
Route::get('/donorhelp','FrontendController@donorhelp')->name('donorhelp');
Route::get('/camp-images/{id}','FrontendController@allcampimages')->name('camp_galleries');


Route::resource('store_Donor','DonorRegistrationController');
Route::post('donor_login','DonorRegistrationController@donor_login')->name('donor_login');

Route::resource('store_request','RequestController');






Route::resource('contact','ContactController');

Route::resource('news','NewsController');
Route::resource('image','ImageController');



Route::get('/searchblood','DonorRegistrationController@searchblood')->name('searchblood');

Auth::routes();

Route::get('/register', function(){
    return redirect()->route('login');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix'=>'admin','middleware'=>['auth','admin']], function(){
    Route::get('/','HomeController@admin')->name('admin');
    Route::resource('camp','CampController');
    Route::resource('donor','DonorController');
    Route::resource('blood_request','AdminRequestController');
    Route::get('/profile','DonorController@adminProfile')->name('admin-profile');          
    Route::put('/profile/{id}','DonorController@UpdateAdmin')->name('admin-update');
    Route::resource('blood','BloodController');
    Route::resource('contact','ContactController');
});



Route::group(['prefix'=>'donor','middleware'=>['auth','donor']], function(){
    Route::get('/','HomeController@donor')->name('donor');
    Route::get('change_profile','DonorPanelController@change_profile')->name('change_profile');
    Route::put('update_profile/{id}','DonorPanelController@update_profile')->name('update_profile');
    Route::get('signout','DonorPanelController@signout')->name('signout');
    Route::resource('donorpanel','DonorPanelController');
    Route::get('donationhistory','DonorPanelController@donationhistory')->name('blood_history');
    Route::get('view_request','DonorPanelController@request_view')->name('request_view');
    Route::get('change_password','DonorPanelController@change_password')->name('change_password');
    Route::put('update_password/{id}','DonorPanelController@update_password')->name('update_password');

});

app/Models/Donor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Donor extends Model
{
    protected $table="users";

    protected $fillable=['name','address','email','password','age','blood_group','status','role','mobile','image','added_by','gender'];

    public function getRules($options='add'){
        return [
            'name'=>'required|string',
             'email'=>(($options == 'add') ? 'required' : 'nullable').'|email|'.(($options == 'add') ? 'unique:users,email' : ''),
            'address'=>'required|string',
            'age'=>'nullable|integer',
            'mobile'=>'required|string',
            'image'=>(($options == 'add') ? 'required' : 'sometimes').'|image|max:5000',
           'password'=>(($options == 'add') ? 'required' : 'nullable').'|string|confirmed',
            'status'=>'required|in:active,inactive',
            'gender'=>'required|in:male,female',
            'role'=>'required|in:admin,donor',
            'blood_group'=>'required|in:a+,a-,b-,b+,ab-,ab+,o+,o-',
        ];
    }
}

app/Http/Controllers/DonorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Donor;
use Illuminate\Support\Facades\Hash;

class DonorController extends Controller
{
    protected $donor= null;
    
    public function __construct(Donor $donor)
    {
      $this->donor= $donor;   
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->donor=$this->donor->orderBy('id','DESC')->where('id','!=',request()->user()->id)->get();
        return view('admin.donor.index')->with('data',$this->donor);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.donor.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules =$this->donor->getRules();
        $request->validate($rules);

        $data =$request->all();
        
        if($request->image){
            $file_name =uploadImage($request->image,'users');
            if($file_name){
                $data['image']=$file_name;
            }else{
                $data['image']=null;
            }
        }
        $data['password']=Hash::make($request->password);
       
        $data['added_by']=$request->user()->id;
        $this->donor->fill($data);
        $success= $this->donor->save();
        if($success){
            $request->session()->flash('success','User added successfully');
        }else{
            $request->session()->flash('error','sorry please try again');
        }
        return redirect()->route('donor.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->donor =$this->donor->find($id);
        if(!$this->donor){
            request()->session()->flash('error','donor not found');
            return redirect()->route('donor.index');
        }
        return view('admin.donor.form')->with('donor_data',$this->donor);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd($request);
        $this->donor= $this->donor->find($id);
        if(!$this->donor){
            request()->session()->flash('error','donor not found');
            return redirect()->route('donor.index');
        }

        $rules =$this->donor->getRules('update');
        $request->validate($rules);
       // dd($request);
       
        $data =$request->all();
        $data['email']=$this->donor->email;
        if($request->change_password){
            $data['password']= Hash::make($data['password']);
        }else{
            unset($data['password']);
        }

       
        $image=$this->donor->image;
        if($request->image){
            $file_name =uploadImage($request->image,'users');
            if($file_name){
                $data['image']=$file_name;
                if(!empty($image) && file_exists(public_path().'/images/users/'.$image)){
                    unlink(public_path().'/images/users/'.$image);
                }
            }
        }

       
        $this->donor->fill($data);
        $success =$this->donor->save();
        if($success){
            $request->session()->flash('success','donor updated successfully');
        }else{
            $request->session()->flash('error',' error while updating donor ');
        }
        return redirect()->route('donor.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->donor=$this->donor->find($id);
        if(!$this->donor){
            request()->session()->flash('error','donor not found');
            return redirect()->route('donor.index');
        }
        $image=$this->donor->image;
        $success=$this->donor->delete();
        if($success){
            if(!empty($image) && file_exists(public_path().'/images/users/'.$image)){
                unlink(public_path().'/images/users/'.$image);
            }
            request()->session()->flash('success','donor deleted successfully');
             
        }else{
            request()->session()->flash('error','donor not deleted');  
        }
        return redirect()->route('donor.index');
    }





    public function adminProfile(){
        $this->donor =$this->donor->find(request()->user()->id);
        if(!$this->donor){
            request()->session()->flash('error','donor not found');
            return redirect()->route('donor.index');
        }
        return view('admin.donor.admin-form')->with('donor_data',$this->donor);
    }



    public function UpdateAdmin(Request $request ,$id){
        $request->request->add(['role'=>'admin']);
        $request->request->add(['status'=>'active']);
        


        $rules =$this->donor->getRules('update');
        $request->validate($rules);

        $data =$request->all();
        if($request->change_password){
            $data['password']= Hash::make($data['password']);
        }else{
            unset($data['password']);
            
        }

        $this->donor= $this->donor->find($id);
        $this->donor->fill($data);
        $success =$this->donor->save();
        if($success){
            $request->session()->flash('success','Admin  updated successfully');
        }else{
            $request->session()->flash('error',' error while updating Admin ');
        }
        return redirect()->route('donor.index');
    }
}

resources/views/admin/donor/form.blade.php
@extends('layouts.admin-dashboard')
@section('scripts')
<script>
    $('#change_password').change(function(){
        var checked =$('#change_password').prop('checked');
        if(checked){
            $('#password').attr('required');
            $('#password_confirm').attr('required');
            $('#change_password_div').removeClass('hidden');
        }else{
            $('#password').removeAttr('required');
            $('#password_confirm').removeAttr('required');
            $('#change_password_div').addClass('hidden');
        }
    });
</script>


<script>
    function myFunction() {
  var x = document.getElementById("password");
  if (x.type === "password") {
    x.type = "text";
  } else {
    x.type = "password";
  }
}

function myFunction1() {
  var x = document.getElementById("confirm_password");
  if (x.type === "password") {
    x.type = "text";
  } else {
    x.type = "password";
  }
}


</script>

@endsection

@section('content')


<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Donor {{ isset($donor_data) ? 'update' : 'add' }} page</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">

                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Donor Page</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        {{ isset($donor_data) ? 'update' : 'add' }} Donor to the page ...
                        <div>

                            @if(isset($donor_data))
                            {{ Form::open(['url'=>route('donor.update',$donor_data->id),'class'=>'form','enctype'=>'multipart/form-data']) }}
                            @method('PUT')

                            @else

                            {{ Form::open(['url'=>route('donor.store'),'class'=>'form','enctype'=>'multipart/form-data']) }}

                            @endif

                            @csrf
                            



                            <div class="form-group row">
                                {{ Form::label('name','Name: ',['class'=>'col-sm-3'])}}
                                <div class="col-sm-9">
                                    {{ Form::text('name',@$donor_data->name,['class'=>'form-control','id'=>'name']) }}
                                    @if($errors->has('name'))
                                    <span class="alert-danger">
                                        {{ $errors->first('name')}}
                                    </span>
                                    @endif
                                </div>
                            </div>

                           
                            <div class="form-group row" style="display: {{isset($donor_data) ? 'none' : 'block' }}">
                            {{ Form::label('email', 'Email: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::text('email', @$donor_data->email ,['class'=>'form-control','id'=>'email','rows'=>5,'style'=>'resize:none']) }}
                                @if($errors->has('email'))
                                <span class="alert-danger">{{ $errors->first('email') }}</span>
                                @endif
                            </div>
                        </div>




                            <div class="form-group row">
                                {{ Form::label('age','Age: ',['class'=>'col-sm-3'])}}
                                <div class="col-sm-9">
                                    {{ Form::number('age',@$donor_data->age,['class'=>'form-control','id'=>'age']) }}
                                    @if($errors->has('age'))
                                    <span class="alert-danger">
                                        {{ $errors->first('age')}}
                                    </span>
                                    @endif
                                </div>
                            </div>



                            <div class="form-group row">
                                {{ Form::label('address','Address: ',['class'=>'col-sm-3']) }}
                                <div class="col-sm-9">
                                    {{Form::textarea('address',@$donor_data->address,['class'=>'form-control','id'=>'address']) }}
                                    @if($errors->has('address'))
                                    <span class="alert-danger">
                                        {{ $errors->first('address') }}
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row">
                                {{ Form::label('mobile','Contact number: ',['class'=>'col-sm-3'])}}
                                <div class="col-sm-9">
                                   <input type="tel" name="mobile" class="form-control" value="{{ @$donor_data->mobile}}">
                                    @if($errors->has('mobile'))
                                    <span class="alert-danger">
                                        {{ $errors->first('mobile')}}
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                {{ Form::label('status','Status: ',['class'=>'col-sm-3']) }}
                                <div class="col-sm-9">
                                    {{Form::select('status',['active'=>'Active','inactive'=>'Inactive'],@$donor_data->status,['class'=>'form-control','id'=>'status']) }}
                                    @if($errors->has('status'))
                                    <span class="alert-danger">
                                        {{ $errors->first('status') }}
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                {{ Form::label('role','Role: ',['class'=>'col-sm-3']) }}
                                <div class="col-sm-9">
                                    {{Form::select('role',['admin'=>'Admin','donor'=>'Donor'],@$donor_data->role,['class'=>'form-control','id'=>'role']) }}
                                    @if($errors->has('role'))
                                    <span class="alert-danger">
                                        {{ $errors->first('role') }}
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                {{ Form::label('gender','Gender: ',['class'=>'col-sm-3']) }}
                                <div class="col-sm-9">
                                    {{Form::select('gender',['male'=>'Male','female'=>'Female'],@$donor_data->gender,['class'=>'form-control','id'=>'gender']) }}
                                    @if($errors->has('gender'))
                                    <span class="alert-danger">
                                        {{ $errors->first('gender') }}
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                {{ Form::label('blood_group','Blood: ',['class'=>'col-sm-3']) }}
                                <div class="col-sm-9">
                                    {{Form::select('blood_group',[''=>'Select any one','a+'=>'A+','a-'=>'A-','b+'=>'B+','b-'=>'B-','ab+'=>'AB+','ab-'=>'AB-','o+'=>'O+','o-'=>'O-'],@$donor_data->blood_group,['class'=>'form-control','id'=>'blood_group']) }}
                                    @if($errors->has('blood_group'))
                                    <span class="alert-danger">
                                        {{ $errors->first('blood_group') }}
                                    </span>
                                    @endif
                                </div>
                            </div>


                            @if(isset($donor_data))

                        <div class="form-group row" style=" isset($donor_data) ? 'none' : 'block'  ">
                            {{ Form::label('change_password', 'Change password: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::checkbox('change_password',1,false,['id'=>'change_password']) }} Yes
                                @if($errors->has('change_password'))
                                <span class="alert-danger">{{ $errors->first('change_password') }}</span>
                                @endif
                            </div>
                        </div>
                        @endif


                        <div class=" {{ isset($donor_data)?'hidden':''}}" id="change_password_div">

                        <div class="form-group row" style=" isset($donor_data) ? 'none' : 'block'  ">
                            {{ Form::label('password', 'Password: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::password('password',['id'=>'password','class'=>'form-control']) }}
                                <input type="checkbox" onclick="myFunction()">Show Password
                                @if($errors->has('password'))
                                <span class="alert-danger">{{ $errors->first('password') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row" style=" isset($donor_data) ? 'none' : 'block'  ">
                            {{ Form::label('confirm_password', 'Reenter password: ',['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{Form::password('password_confirmation',['id'=>'confirm_password','class'=>'form-control']) }}
                               
                                <input type="checkbox" onclick="myFunction1()">Show Password
                                @if($errors->has('confirm_password'))
                                <span class="alert-danger">{{ $errors->first('confirm_password') }}</span>
                                @endif
                            </div>
                        </div>

                        </div>







                            <div class="form-group row">
                                {{ Form::label('image','Image: ',['class'=>'col-sm-3']) }}
                                <div class="col-sm-4">
                                    {{Form::file('image',['class'=>'form-control','id'=>'image','accept'=>'image/*']) }}
                                    @if($errors->has('image'))
                                    <span class="alert-danger">
                                        {{ $errors->first('image') }}
                                    </span>
                                    @endif
                                </div>
                                @if(isset($donor_data))
                                @if( $donor_data->image != null && file_exists(public_path().'/images/users/'.$donor_data->image))
                                <div class="col-4">
                                    <img style="width:150px" src="{{ asset('images/users/'.$donor_data->image) }}" alt="" class="img img-responsive img-thumbnail">

                                </div>
                                @endif
                                @endif
                            </div>



                            <div class="form-group row">
                                {{ Form::label('','',['class'=>'col-sm-3']) }}
                                <div class="col-sm-9">
                                    {{ Form::button('<i class ="fas fa-plane"></i>  submit ' , ['type'=>'submit','class'=>'btn btn-success']) }}
                                    {{ Form::button('<i class ="fas fa-trash"></i> cancel' , ['type'=>'reset','class'=>'btn alert-danger']) }}
                                </div>
                            </div>

                            {{Form::close()}}




                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/admin/donor/index.blade.php
@extends('layouts.admin-dashboard')@section('links')
    <link rel="stylesheet" href="{{ asset('assets/admin/css/jquery.dataTables.min.css')}}">
@endsection

@section('scripts')
        <script src= "{{ asset('assets/admin/js/jquery.dataTables.min.js')}}" ></script>
        <script>
            $('.table').dataTable();

        </script>
@endsection


@section('content')



<div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Donor add page</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">

                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Donor Page</h2>

                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                      Add Donor to the page ...
                      <div>
                          @include('admin.section.notification')
                      <div>
                          <a href="{{ route('donor.create')}}" class="btn btn-success  pull-right "><i class="fas fa-plus"></i> Add Donor</a>
                      </div>
                          <table class="table  jambo_table">
                                <thead>
                                    <th>S.n </th>
                                    <th>Name</th>
                                    <th>Address </th>
                                    <th>Mobile no. </th>
                                    <th>Email </th>
                                    <th>Role </th>
                                    <th>Gender </th>
                                    <th>Status </th>
                                    <th>image </th>
                                    <th>action </th>
                                </thead>
                                <tbody>
                                    @if($data)
                                    @foreach($data as $key=>$value)
                                  <tr>
                                      <td> {{ $key+1 }}</td>
                                      <td>{{$value->name}}</td>
                                      <td>{{ $value->address }}</td>
                                      <td>{{ $value->mobile }}</td>
                                      <td>{{ $value->email }}</td>
                                      <td>{{ $value->role }}</td>
                                      <td>{{ $value->gender }}</td>
                                   
                                      <!-- <td>{{ $value->description }}</td> -->
                                      <td>{{ $value->status }}</td>
                                       <td>
                                            @if($value->image != null && file_exists(public_path().'/images/users/'.$value->image) )
                                        <img style="max-width:100px" src="{{ asset('images/users/'.$value->image)}}" alt="" class="img img-responsive img-thumbnail" >
                                          @else 
                                          <h4>No image found</h4>   
                                        @endif
                                        </td>
                                      <td>
                                          <a href="{{ route('donor.edit',$value->id)}}" class="btn btn-success"style="border-radius:50%"> <i class="fas fa-pencil-alt"></i></a>



                                        <form action="{{ route('donor.destroy',$value->id) }}" method="post" onsubmit="return confirm('Are you sure to delete the Donor') ">
                                        @method('DELETE')
                                        @csrf
                                        <button class="btn btn-danger"style="border-radius:50%"  type="submit"> <i class="fas fa-trash"></i></button>



                                        </form>
                                    </td>

                                  </tr>
                                  @endforeach
                                    @endif
                                </tbody>

                          </table>
                      </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>




@endsection